version: "3"

services:
  app:
    image: task-api:latest
    build:
      dockerfile: ./Dockerfile
      context: ./task-api
    volumes:
      - ./task-api/src:/src
      - ./task-api/docker-entrypoint.sh:/docker-entrypoint.sh
    environment:
      - PORT=8000
      - HOST=0.0.0.0
    env_file:
      - ./.env
    command: ["-start-service"]
    expose:
      - "8000"
    ports:
      - "8000:8000"
      - "5779:5678"

